/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorAnio;
import Controlador.ControladorEditorial;
import Controlador.ControladorEstado;
import Controlador.ControladorISBN;
import Controlador.ControladorIdioma;
import Controlador.ControladorLibro;
import Controlador.ControladorTitulo;
import Controlador.ControladorUtilidad;
import Modelo.AnioPublicacion;
import Modelo.Autor;
import Modelo.Editorial;
import Modelo.Estado;
import Modelo.ISBN;
import Modelo.Idioma;
import Modelo.Libro;
import Modelo.TituloLibro;
import Modelo.Utilidad;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class BuscarLibro extends javax.swing.JPanel {

    private ControladorEditorial cE = new ControladorEditorial();
    ArrayList<Editorial> listaE = cE.listado();

    private ControladorUtilidad cU = new ControladorUtilidad();
    ArrayList<Utilidad> listaU = cU.listado();

    private ControladorTitulo cT = new ControladorTitulo();
    ArrayList<TituloLibro> listaT = cT.listado();

    private ControladorEstado cEs = new ControladorEstado();
    ArrayList<Estado> listaEs = cEs.listado();

    private ControladorAnio cA = new ControladorAnio();
    ArrayList<AnioPublicacion> listaA = cA.listado();

    private ControladorISBN cIS = new ControladorISBN();
    ArrayList<ISBN> listaIS = cIS.listado();

    private ControladorIdioma cID = new ControladorIdioma();
    ArrayList<Idioma> listaIdioma = cID.listado();

    private ControladorLibro cL = new ControladorLibro();

    private Libro l = null;

    /**
     * Creates new form MenuPrincipal
     */
    public BuscarLibro() {
        initComponents();
        this.setPreferredSize(Principal.dimension);
        this.setMinimumSize(Principal.dimension);
        this.setMaximumSize(Principal.dimension);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        campos(false);

    }

    private void campos(boolean op) {
        boxAnio.setEnabled(op);
        boxEditorial.setEnabled(op);
        boxEstado.setEnabled(op);
        boxISBN.setEnabled(op);
        boxTitulo.setEnabled(op);
        boxUtilidad.setEnabled(op);
        txtNroPaginas.setEnabled(op);
        txtPrecio.setEnabled(op);
        boxIdioma.setEnabled(op);
    }

    private void limpiarCampos() {
        boxAnio.setSelectedIndex(-1);
        boxEditorial.setSelectedIndex(-1);
        boxEstado.setSelectedIndex(-1);
        boxISBN.setSelectedIndex(-1);
        boxTitulo.setSelectedIndex(-1);
        boxUtilidad.setSelectedIndex(-1);
        boxIdioma.setSelectedIndex(-1);
        txtNroPaginas.setText("");
        txtPrecio.setText("");
        // txtNroSerie.setText("");
    }

    private void llenarbox() {

        for (int i = 0; i < listaT.size(); i++) {
            boxTitulo.addItem(listaT.get(i).getTitulo());
        }

        for (int i = 0; i < listaIdioma.size(); i++) {
            boxIdioma.addItem(listaIdioma.get(i).getIdioma());
        }

        for (int i = 0; i < listaE.size(); i++) {
            boxEditorial.addItem(listaE.get(i).getNombre_editorial());
        }

        for (int i = 0; i < listaU.size(); i++) {
            boxUtilidad.addItem(listaU.get(i).getDescripcion());
        }

        for (int i = 0; i < listaEs.size(); i++) {
            boxEstado.addItem(listaEs.get(i).getEstado());
        }

        for (int i = 0; i < listaA.size(); i++) {
            boxAnio.addItem(String.valueOf(listaA.get(i).getAnio()));
        }

        for (int i = 0; i < listaIS.size(); i++) {
            boxISBN.addItem(listaIS.get(i).getISBN());
        }
    }

    private void btnVolverDefault() {
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/volver-default.png")));
    }

    private void btnVolverSelected() {
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/volver-selected.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNroSerie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        boxTitulo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        boxEditorial = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        boxUtilidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        boxEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        boxAnio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        boxISBN = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtNroPaginas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        Autores = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        boxIdioma = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JLabel();
        contenedorSecundario = new javax.swing.JLabel();
        contenedorPrincipal = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1382, 744));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(66, 66, 66));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Felix Titling", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero de Serie:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 70, 100, 16);
        jPanel1.add(txtNroSerie);
        txtNroSerie.setBounds(210, 70, 150, 24);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Título:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 120, 40, 16);

        jPanel1.add(boxTitulo);
        boxTitulo.setBounds(200, 120, 260, 26);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Editorial:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 200, 60, 16);

        jPanel1.add(boxEditorial);
        boxEditorial.setBounds(200, 200, 260, 26);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Utilidad:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 240, 50, 16);

        jPanel1.add(boxUtilidad);
        boxUtilidad.setBounds(200, 240, 260, 26);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 280, 50, 16);

        jPanel1.add(boxEstado);
        boxEstado.setBounds(200, 280, 260, 26);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año de Publicacion:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 320, 120, 16);

        jPanel1.add(boxAnio);
        boxAnio.setBounds(200, 320, 260, 26);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ISBN:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 360, 41, 16);

        jPanel1.add(boxISBN);
        boxISBN.setBounds(200, 360, 260, 26);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numero de Páginas:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 400, 120, 16);
        jPanel1.add(txtNroPaginas);
        txtNroPaginas.setBounds(200, 400, 150, 24);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Precio de Referencia:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 440, 130, 16);
        jPanel1.add(txtPrecio);
        txtPrecio.setBounds(200, 440, 150, 24);

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(380, 60, 71, 32);

        Autores.setForeground(new java.awt.Color(255, 255, 255));
        Autores.setText("Idioma:");
        jPanel1.add(Autores);
        Autores.setBounds(140, 160, 41, 20);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);
        btnEditar.setBounds(520, 210, 100, 50);

        jPanel1.add(boxIdioma);
        boxIdioma.setBounds(200, 160, 260, 26);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(580, 450, 76, 32);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(490, 450, 90, 32);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(410, 450, 77, 32);

        add(jPanel1);
        jPanel1.setBounds(540, 110, 660, 490);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/volver-default.png"))); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        add(btnVolver);
        btnVolver.setBounds(110, 564, 170, 50);

        contenedorSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/contenedor-secundario.png"))); // NOI18N
        add(contenedorSecundario);
        contenedorSecundario.setBounds(480, 60, 770, 590);

        contenedorPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/contenedor-main.png"))); // NOI18N
        add(contenedorPrincipal);
        contenedorPrincipal.setBounds(40, 70, 300, 580);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/wallpapers/wallpaper.jpg"))); // NOI18N
        wallpaper.setPreferredSize(Principal.dimension);
        add(wallpaper);
        wallpaper.setBounds(0, 0, 2558, 1562);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        l = cL.buscar(Integer.parseInt(txtNroSerie.getText()));

        if (l != null) {
            limpiarCampos();
            llenarbox();
            for (int i = 0; i < boxEditorial.getItemCount(); i++) {
                boxEditorial.setSelectedIndex(i);
                if (String.valueOf(boxEditorial.getSelectedItem()).equals(l.getEditorial())) {
                    break;
                }
            }

            boxIdioma.setSelectedIndex(new ControladorIdioma().buscar(l.getNro_serie()) - 1);

            for (int i = 0; i < boxAnio.getItemCount(); i++) {
                boxAnio.setSelectedIndex(i);
                if (String.valueOf(boxAnio.getSelectedItem()).equals(String.valueOf(l.getAnio_publicacion()))) {
                    break;
                }
            }

            for (int i = 0; i < boxEstado.getItemCount(); i++) {
                boxEstado.setSelectedIndex(i);
                if (String.valueOf(boxEstado.getSelectedItem()).equals(l.getEstado())) {
                    break;
                }
            }

            for (int i = 0; i < boxISBN.getItemCount(); i++) {
                boxISBN.setSelectedIndex(i);
                if (String.valueOf(boxISBN.getSelectedItem()).equals(l.getISBN())) {
                    break;
                }
            }
            for (int i = 0; i < boxTitulo.getItemCount(); i++) {
                boxTitulo.setSelectedIndex(i);
                if (String.valueOf(boxTitulo.getSelectedItem()).equals(l.getTitulo())) {
                    break;
                }
            }
            for (int i = 0; i < boxUtilidad.getItemCount(); i++) {
                boxUtilidad.setSelectedIndex(i);
                if (String.valueOf(boxUtilidad.getSelectedItem()).equals(l.getUtilidad())) {
                    break;
                }
            }
            txtNroPaginas.setText(String.valueOf(l.getNro_paginas()));
            txtPrecio.setText( String.valueOf(l.getPrecio_referencia()));

        } else {
            JOptionPane.showMessageDialog(null, "No se ha encontrado ningún libro con este numero de serie");
        }


    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolverSelected();
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolverDefault();
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        btnVolverDefault();
        limpiarCampos();
        Principal.principal.MenuPrinicipal();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (l != null) {
            campos(true);
            btnGuardar.setEnabled(true);
            btnCancelar.setEnabled(true);
            btnEliminar.setEnabled(false);
            txtNroSerie.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Antes debes buscar un Libro");
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (l == null) {
            JOptionPane.showMessageDialog(null, "Debes Buscar un libro si quieres Eliminar");
        } else {
            int op = JOptionPane.showConfirmDialog(null, "Está seguro que desea eliminar el libro con Numero de Serie: " + l.getNro_serie());
            if (op == 0) {
                if (new ControladorLibro().eliminar(l.getNro_serie())) {
                    limpiarCampos();
                    txtNroSerie.setText("");
                    JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "ha ocurrido un error al intentar eliminar");
                }

            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnBuscarMouseClicked(null);
        campos(false);
        txtNroSerie.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        l.setIDISBN(boxISBN.getSelectedIndex() + 1);
        l.setIDanio_publicacion(boxAnio.getSelectedIndex() + 1);
        l.setIDeditorial(boxEditorial.getSelectedIndex() + 1);
        l.setIDestado(boxEstado.getSelectedIndex() + 1);
        l.setIDtitulo(boxTitulo.getSelectedIndex() + 1);
        l.setIDutilidad(boxUtilidad.getSelectedIndex() + 1);
        l.setNro_paginas(Integer.parseInt(txtNroPaginas.getText()));
        l.setPrecio_referencia(Float.parseFloat(txtPrecio.getText()));  
        
       
        if(new ControladorLibro().modificar(l, boxIdioma.getSelectedIndex() + 1)){
            JOptionPane.showMessageDialog(null, "Se ha Modificado Correctamente");
            btnCancelarActionPerformed(null);
        }else{
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al tratar de modificar");
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autores;
    private javax.swing.JComboBox<String> boxAnio;
    private javax.swing.JComboBox<String> boxEditorial;
    private javax.swing.JComboBox<String> boxEstado;
    private javax.swing.JComboBox<String> boxISBN;
    private javax.swing.JComboBox<String> boxIdioma;
    private javax.swing.JComboBox<String> boxTitulo;
    private javax.swing.JComboBox<String> boxUtilidad;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JLabel contenedorPrincipal;
    private javax.swing.JLabel contenedorSecundario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNroPaginas;
    private javax.swing.JTextField txtNroSerie;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
