/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

---NOTA 20-05-2018 0:58---
Falta agregar iconos al contenedor3
configurar acciones de botones panel detalle con los mantenedores, selectores
y visibilidad de iconos en el contenedor3

*recomendacion*
    usar como referencia el codigo usado para las acciones de botones(Entred, 
Exited, Clicked), selectores y visibilidad de iconos del contenedorPrincipal 
y contenedorSecunadario.



 */
package Vista;

/**
 *
 * @author Daniel
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    private boolean mantenerLibros = false;
    private boolean mantenerDetalles = false;
    private boolean mantenerDistribuidor = false;
    private boolean mantenerFactura = false;
    private boolean mantenerMetodoPago = false;
    private boolean mantenerCompra = false;
    private boolean mantenerAutor = false;
    private boolean mantenerEditorial = false;
    private boolean mantenerCategoria = false;
    private boolean mantenerIdioma = false;
    private boolean mantenerEstado = false;
    private boolean mantenerTitulo = false;

    public MenuPrincipal() {
        initComponents();
        this.setPreferredSize(Principal.dimension);
        this.setMinimumSize(Principal.dimension);
        this.setMaximumSize(Principal.dimension);
        selectores(false);
        panelVisible(false);
        panelDetalleVisible(false);
        panel3Visible(false);

    }

    private void selectores(boolean visi) {
        selectorCompra.setVisible(visi);
        selectorDetalles.setVisible(visi);
        selectorDistribuidor.setVisible(visi);
        selectorFactura.setVisible(visi);
        selectorLibros.setVisible(visi);
        selectorMetodoPago.setVisible(visi);
        iconoLibro.setVisible(visi);
        iconoDistribuidor.setVisible(visi);
        iconoFactura.setVisible(visi);
        iconoMetodoPago.setVisible(visi);
        iconoCompra.setVisible(visi);
        selectorTitulo.setVisible(visi);
        selectorAutor.setVisible(visi);
        selectorEditorial.setVisible(visi);
        selectorDetalles.setVisible(visi);
        selectorCategoria.setVisible(visi);
        selectorIdioma.setVisible(visi);
        selectorEstado.setVisible(visi);
        iconoTitulo.setVisible(visi);
        iconoAutor.setVisible(visi);
        iconoEditorial.setVisible(visi);
        iconoCategoria.setVisible(visi);
        iconoIdioma.setVisible(visi);
        iconoEstado.setVisible(visi);

    }

    private void selectoresDetalle(boolean visi) {
        selectorTitulo.setVisible(visi);
        selectorAutor.setVisible(visi);
        selectorEditorial.setVisible(visi);
        selectorCategoria.setVisible(visi);
        selectorIdioma.setVisible(visi);
        selectorEstado.setVisible(visi);
    }

    private void panelVisible(boolean visible) {
        contenedorSecundario.setVisible(visible);
        btnRegistrar.setVisible(visible);
        btnBuscar.setVisible(visible);
        btnMostrar.setVisible(visible);
    }

    private void panelDetalleVisible(boolean visi) {
        contenedorSecundarioDetalle.setVisible(visi);
        btnTitulo.setVisible(visi);
        btnAutor.setVisible(visi);
        btnEditorial.setVisible(visi);
        btnCategoria.setVisible(visi);
        btnIdioma.setVisible(visi);
        btnEstado.setVisible(visi);
    }

    private void panel3Visible(boolean visible) {
        contenedor3.setVisible(visible);
        btnRegistrarDetalle.setVisible(visible);
        btnBuscarDetalle.setVisible(visible);
        btnMostrarDetalle.setVisible(visible);
    }

    private void reinicioDetalle() {
        mantenerAutor = false;
        mantenerEditorial = false;
        mantenerCategoria = false;
        mantenerIdioma = false;
        mantenerEstado = false;
        selectoresDetalle(false);
        btnTituloDefault();
        iconoTitulo.setVisible(false);
        btnAutorDefault();
        iconoAutor.setVisible(false);
        btnEditorialDefault();
        iconoEditorial.setVisible(false);
        btnCategoriaDefault();
        iconoCategoria.setVisible(false);
        btnIdiomaDefault();
        iconoIdioma.setVisible(false);
        btnEstadoDefault();
        iconoEstado.setVisible(false);
        panel3Visible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void btnLibrosDefault() {
        btnLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/libros-default.png")));
    }

    private void btnLibrosSelected() {
        btnLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/libros-selected.png")));
    }

    private void btnDistribuidoresDefault() {
        btnDistribuidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/distribuidor-default.png")));
    }

    private void btnDistribuidoresSelected() {
        btnDistribuidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/distribuidor-selected.png")));
    }

    private void btnFacturasDefault() {
        btnFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/factura-default.png")));
    }

    private void btnFacturasSelected() {
        btnFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/factura-selected.png")));
    }

    private void btnDetallesDefatult() {
        btnDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/detalles-default.png")));
    }

    private void btnDetallesSelected() {
        btnDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/detalles-selected.png")));
    }

    private void btnMetodoPagoDefault() {
        btnMetodoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/metodoPago-default.png")));
    }

    private void btnMetodoPagoSelected() {
        btnMetodoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/metodoPago-selected.png")));
    }

    private void btnCompraDefault() {
        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/compra-default.png")));
    }

    private void btnCompraSelected() {
        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/compra-selected.png")));
    }

    private void btnRegistrarDefault() {
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/registrar-default.png")));
    }

    private void btnRegistrarSelected() {
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/registrar-selected.png")));
    }

    private void btnBuscarDefault() {
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/buscar-default.png")));
    }

    private void btnBuscarSelected() {
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/buscar-selected.png")));
    }

    private void btnMostrarDefault() {
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/mostrarTodo-default.png")));
    }

    private void btnMostrarSelected() {
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/mostrarTodo-selected.png")));
    }

    private void btnAutorDefault() {
        btnAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/autor-default.png")));
    }

    private void btnAutorSelected() {
        btnAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/autor-selected.png")));
    }

    private void btnEditorialDefault() {
        btnEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/editorial-default.png")));
    }

    private void btnEditorialSelected() {
        btnEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/editorial-selected.png")));
    }

    private void btnCategoriaDefault() {
        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/categoria-default.png")));
    }

    private void btnCategoriaSelected() {
        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/categoria-selected.png")));
    }

    private void btnIdiomaDefault() {
        btnIdioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/idioma-default.png")));
    }

    private void btnIdiomaSelected() {
        btnIdioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/idioma-selected.png")));
    }

    private void btnEstadoDefault() {
        btnEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/estado-default.png")));
    }

    private void btnEstadoSelected() {
        btnEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/estado-selected.png")));
    }

    private void btnRegistrarDetalleDefault() {
        btnRegistrarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/registrar-default.png")));
    }

    private void btnRegistrarDetalleSelected() {
        btnRegistrarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/registrar-selected.png")));
    }

    private void btnBuscarDetalleDefault() {
        btnBuscarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/buscar-default.png")));
    }

    private void btnBuscarDetalleSelected() {
        btnBuscarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/buscar-selected.png")));
    }

    private void btnMostrarDetalleDefault() {
        btnMostrarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/mostrarTodo-default.png")));
    }

    private void btnTituloDefault() {
        btnTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/titulo-default.png")));
    }

    private void btnTituloSelected() {
        btnTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/titulo-selected.png")));
    }

    private void btnMostrarDetalleSelected() {
        btnMostrarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/mostrarTodo-selected.png")));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconoTitulo = new javax.swing.JLabel();
        iconoEstado = new javax.swing.JLabel();
        iconoIdioma = new javax.swing.JLabel();
        iconoCategoria = new javax.swing.JLabel();
        iconoEditorial = new javax.swing.JLabel();
        iconoAutor = new javax.swing.JLabel();
        btnMostrarDetalle = new javax.swing.JLabel();
        btnBuscarDetalle = new javax.swing.JLabel();
        btnRegistrarDetalle = new javax.swing.JLabel();
        contenedor3 = new javax.swing.JLabel();
        selectorTitulo = new javax.swing.JLabel();
        selectorEstado = new javax.swing.JLabel();
        selectorIdioma = new javax.swing.JLabel();
        selectorCategoria = new javax.swing.JLabel();
        selectorEditorial = new javax.swing.JLabel();
        selectorAutor = new javax.swing.JLabel();
        btnEstado = new javax.swing.JLabel();
        btnIdioma = new javax.swing.JLabel();
        btnCategoria = new javax.swing.JLabel();
        btnEditorial = new javax.swing.JLabel();
        btnTitulo = new javax.swing.JLabel();
        btnAutor = new javax.swing.JLabel();
        contenedorSecundarioDetalle = new javax.swing.JLabel();
        iconoCompra = new javax.swing.JLabel();
        iconoMetodoPago = new javax.swing.JLabel();
        iconoFactura = new javax.swing.JLabel();
        iconoDistribuidor = new javax.swing.JLabel();
        iconoLibro = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JLabel();
        selectorCompra = new javax.swing.JLabel();
        selectorMetodoPago = new javax.swing.JLabel();
        selectorFactura = new javax.swing.JLabel();
        selectorDistribuidor = new javax.swing.JLabel();
        selectorDetalles = new javax.swing.JLabel();
        selectorLibros = new javax.swing.JLabel();
        btnCompra = new javax.swing.JLabel();
        btnMetodoPago = new javax.swing.JLabel();
        btnFacturas = new javax.swing.JLabel();
        btnDistribuidores = new javax.swing.JLabel();
        btnDetalles = new javax.swing.JLabel();
        btnLibros = new javax.swing.JLabel();
        contenedorSecundario = new javax.swing.JLabel();
        contenedorPrincipal = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1382, 744));
        setLayout(null);

        iconoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/icono-titulo.png"))); // NOI18N
        add(iconoTitulo);
        iconoTitulo.setBounds(1000, 190, 260, 270);

        iconoEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/done.png"))); // NOI18N
        add(iconoEstado);
        iconoEstado.setBounds(1000, 190, 260, 270);

        iconoIdioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/language.png"))); // NOI18N
        add(iconoIdioma);
        iconoIdioma.setBounds(1000, 190, 260, 270);

        iconoCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/four-black-squares.png"))); // NOI18N
        add(iconoCategoria);
        iconoCategoria.setBounds(1000, 190, 260, 270);

        iconoEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/layer.png"))); // NOI18N
        add(iconoEditorial);
        iconoEditorial.setBounds(1000, 190, 260, 270);

        iconoAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/author-sign.png"))); // NOI18N
        add(iconoAutor);
        iconoAutor.setBounds(1000, 190, 260, 270);

        btnMostrarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/mostrarTodo-default.png"))); // NOI18N
        btnMostrarDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarDetalleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarDetalleMouseExited(evt);
            }
        });
        add(btnMostrarDetalle);
        btnMostrarDetalle.setBounds(740, 460, 169, 70);

        btnBuscarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/buscar-default.png"))); // NOI18N
        btnBuscarDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarDetalleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarDetalleMouseExited(evt);
            }
        });
        add(btnBuscarDetalle);
        btnBuscarDetalle.setBounds(740, 310, 169, 50);

        btnRegistrarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/registrar-default.png"))); // NOI18N
        btnRegistrarDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarDetalleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarDetalleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarDetalleMouseExited(evt);
            }
        });
        add(btnRegistrarDetalle);
        btnRegistrarDetalle.setBounds(740, 180, 169, 50);

        contenedor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/contenedor3.png"))); // NOI18N
        add(contenedor3);
        contenedor3.setBounds(710, 120, 640, 470);

        selectorTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        selectorTitulo.setToolTipText("");
        add(selectorTitulo);
        selectorTitulo.setBounds(500, 130, 24, 30);

        selectorEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        selectorEstado.setToolTipText("");
        add(selectorEstado);
        selectorEstado.setBounds(500, 480, 24, 30);

        selectorIdioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        selectorIdioma.setToolTipText("");
        add(selectorIdioma);
        selectorIdioma.setBounds(500, 410, 24, 30);

        selectorCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        selectorCategoria.setToolTipText("");
        add(selectorCategoria);
        selectorCategoria.setBounds(500, 340, 24, 30);

        selectorEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        selectorEditorial.setToolTipText("");
        add(selectorEditorial);
        selectorEditorial.setBounds(500, 270, 24, 30);

        selectorAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        selectorAutor.setToolTipText("");
        add(selectorAutor);
        selectorAutor.setBounds(500, 200, 24, 30);

        btnEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/estado-default.png"))); // NOI18N
        btnEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstadoMouseExited(evt);
            }
        });
        add(btnEstado);
        btnEstado.setBounds(530, 470, 170, 50);

        btnIdioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/idioma-default.png"))); // NOI18N
        btnIdioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIdiomaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIdiomaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIdiomaMouseExited(evt);
            }
        });
        add(btnIdioma);
        btnIdioma.setBounds(530, 400, 170, 50);

        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/categoria-default.png"))); // NOI18N
        btnCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCategoriaMouseExited(evt);
            }
        });
        add(btnCategoria);
        btnCategoria.setBounds(530, 330, 170, 50);

        btnEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/editorial-default.png"))); // NOI18N
        btnEditorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditorialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditorialMouseExited(evt);
            }
        });
        add(btnEditorial);
        btnEditorial.setBounds(530, 260, 170, 50);

        btnTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/titulo-default.png"))); // NOI18N
        btnTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTituloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTituloMouseExited(evt);
            }
        });
        add(btnTitulo);
        btnTitulo.setBounds(530, 120, 170, 50);

        btnAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/autor-default.png"))); // NOI18N
        btnAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAutorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAutorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAutorMouseExited(evt);
            }
        });
        add(btnAutor);
        btnAutor.setBounds(530, 190, 170, 50);

        contenedorSecundarioDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/contenedor-secundario.png"))); // NOI18N
        add(contenedorSecundarioDetalle);
        contenedorSecundarioDetalle.setBounds(480, 60, 770, 590);

        iconoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/icono-compra.png"))); // NOI18N
        iconoCompra.setText("iconoMetodoPago.setVisible(false);");
        add(iconoCompra);
        iconoCompra.setBounds(920, 310, 260, 210);

        iconoMetodoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/icono-metodoPago.png"))); // NOI18N
        iconoMetodoPago.setText("iconoMetodoPago.setVisible(false);");
        add(iconoMetodoPago);
        iconoMetodoPago.setBounds(920, 310, 260, 256);

        iconoFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/icono-factura.png"))); // NOI18N
        add(iconoFactura);
        iconoFactura.setBounds(920, 310, 260, 270);

        iconoDistribuidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/delivery-van.png"))); // NOI18N
        add(iconoDistribuidor);
        iconoDistribuidor.setBounds(920, 310, 260, 210);

        iconoLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/open-book.png"))); // NOI18N
        add(iconoLibro);
        iconoLibro.setBounds(920, 310, 260, 210);

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/mostrarTodo-default.png"))); // NOI18N
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarMouseExited(evt);
            }
        });
        add(btnMostrar);
        btnMostrar.setBounds(590, 400, 170, 50);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/buscar-default.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        add(btnBuscar);
        btnBuscar.setBounds(590, 310, 170, 50);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/registrar-default.png"))); // NOI18N
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });
        add(btnRegistrar);
        btnRegistrar.setBounds(590, 210, 170, 50);

        selectorCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        add(selectorCompra);
        selectorCompra.setBounds(80, 570, 24, 30);

        selectorMetodoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        add(selectorMetodoPago);
        selectorMetodoPago.setBounds(80, 480, 24, 30);

        selectorFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        add(selectorFactura);
        selectorFactura.setBounds(80, 390, 24, 30);

        selectorDistribuidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        add(selectorDistribuidor);
        selectorDistribuidor.setBounds(80, 300, 24, 30);

        selectorDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        add(selectorDetalles);
        selectorDetalles.setBounds(80, 210, 24, 30);

        selectorLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/right-black-arrow.png"))); // NOI18N
        add(selectorLibros);
        selectorLibros.setBounds(80, 120, 24, 30);

        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/compra-default.png"))); // NOI18N
        btnCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCompraMouseExited(evt);
            }
        });
        add(btnCompra);
        btnCompra.setBounds(110, 560, 170, 50);

        btnMetodoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/metodoPago-default.png"))); // NOI18N
        btnMetodoPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMetodoPagoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMetodoPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMetodoPagoMouseExited(evt);
            }
        });
        add(btnMetodoPago);
        btnMetodoPago.setBounds(110, 470, 170, 50);

        btnFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/factura-default.png"))); // NOI18N
        btnFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFacturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFacturasMouseExited(evt);
            }
        });
        add(btnFacturas);
        btnFacturas.setBounds(110, 380, 170, 50);

        btnDistribuidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/distribuidor-default.png"))); // NOI18N
        btnDistribuidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDistribuidoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDistribuidoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDistribuidoresMouseExited(evt);
            }
        });
        add(btnDistribuidores);
        btnDistribuidores.setBounds(110, 290, 170, 50);

        btnDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/detalles-default.png"))); // NOI18N
        btnDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetallesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetallesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetallesMouseExited(evt);
            }
        });
        add(btnDetalles);
        btnDetalles.setBounds(110, 200, 170, 50);

        btnLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/libros-default.png"))); // NOI18N
        btnLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLibrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibrosMouseExited(evt);
            }
        });
        add(btnLibros);
        btnLibros.setBounds(110, 110, 170, 50);

        contenedorSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/contenedor-secundario.png"))); // NOI18N
        add(contenedorSecundario);
        contenedorSecundario.setBounds(480, 60, 770, 590);

        contenedorPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/contenedor-main.png"))); // NOI18N
        add(contenedorPrincipal);
        contenedorPrincipal.setBounds(40, 70, 300, 580);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/wallpapers/wallpaper.jpg"))); // NOI18N
        wallpaper.setPreferredSize(Principal.dimension);
        wallpaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wallpaperMouseClicked(evt);
            }
        });
        add(wallpaper);
        wallpaper.setBounds(0, 0, 2558, 1562);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLibrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosMouseEntered
        if (!mantenerCompra & !mantenerDetalles & !mantenerDistribuidor & !mantenerFactura & !mantenerMetodoPago) {
            btnLibrosSelected();
            panelVisible(true);
            iconoLibro.setVisible(true);
        }
    }//GEN-LAST:event_btnLibrosMouseEntered

    private void btnLibrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosMouseExited
        if (!mantenerDistribuidor & !mantenerCompra & !mantenerDetalles & !mantenerFactura & !mantenerLibros & !mantenerMetodoPago) {
            btnLibrosDefault();
            panelVisible(false);
            iconoLibro.setVisible(false);
        }
    }//GEN-LAST:event_btnLibrosMouseExited

    private void btnDistribuidoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDistribuidoresMouseEntered
        if (!mantenerCompra & !mantenerDetalles & !mantenerFactura & !mantenerLibros & !mantenerMetodoPago) {
            btnDistribuidoresSelected();
            panelVisible(true);
            iconoDistribuidor.setVisible(true);
        }

    }//GEN-LAST:event_btnDistribuidoresMouseEntered

    private void btnDistribuidoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDistribuidoresMouseExited
        if (!mantenerDistribuidor & !mantenerCompra & !mantenerDetalles & !mantenerFactura & !mantenerLibros & !mantenerMetodoPago) {
            btnDistribuidoresDefault();
            panelVisible(false);
            iconoDistribuidor.setVisible(false);
        }

    }//GEN-LAST:event_btnDistribuidoresMouseExited

    private void btnFacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturasMouseEntered
        if (!mantenerCompra & !mantenerDetalles & !mantenerDistribuidor & !mantenerLibros & !mantenerMetodoPago) {
            btnFacturasSelected();
            panelVisible(true);
            iconoFactura.setVisible(true);
        }
    }//GEN-LAST:event_btnFacturasMouseEntered

    private void btnFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturasMouseExited
        if (!mantenerDistribuidor & !mantenerCompra & !mantenerDetalles & !mantenerFactura & !mantenerLibros & !mantenerMetodoPago) {
            btnFacturasDefault();
            panelVisible(false);
            iconoFactura.setVisible(false);
        }
    }//GEN-LAST:event_btnFacturasMouseExited

    private void btnDetallesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetallesMouseEntered
        if (!mantenerCompra & !mantenerLibros & !mantenerDistribuidor & !mantenerFactura & !mantenerMetodoPago) {
            btnDetallesSelected();
            panelDetalleVisible(true);
        }
    }//GEN-LAST:event_btnDetallesMouseEntered

    private void btnDetallesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetallesMouseExited
        if (!mantenerDistribuidor & !mantenerCompra & !mantenerDetalles & !mantenerFactura & !mantenerLibros & !mantenerMetodoPago) {
            btnDetallesDefatult();
            panelDetalleVisible(false);
        }
    }//GEN-LAST:event_btnDetallesMouseExited

    private void btnMetodoPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMetodoPagoMouseEntered
        if (!mantenerCompra & !mantenerDetalles & !mantenerDistribuidor & !mantenerFactura & !mantenerLibros) {
            btnMetodoPagoSelected();
            panelVisible(true);
            iconoMetodoPago.setVisible(true);
        }
    }//GEN-LAST:event_btnMetodoPagoMouseEntered

    private void btnMetodoPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMetodoPagoMouseExited
        if (!mantenerDistribuidor & !mantenerCompra & !mantenerDetalles & !mantenerFactura & !mantenerLibros & !mantenerMetodoPago) {
            btnMetodoPagoDefault();
            panelVisible(false);
            iconoMetodoPago.setVisible(false);
        }
    }//GEN-LAST:event_btnMetodoPagoMouseExited

    private void btnCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseEntered
        if (!mantenerLibros & !mantenerDetalles & !mantenerDistribuidor & !mantenerFactura & !mantenerMetodoPago) {
            btnCompraSelected();
            panelVisible(true);
            iconoCompra.setVisible(true);
        }
    }//GEN-LAST:event_btnCompraMouseEntered

    private void btnCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseExited
        if (!mantenerDistribuidor & !mantenerCompra & !mantenerDetalles & !mantenerFactura & !mantenerLibros & !mantenerMetodoPago) {
            btnCompraDefault();
            panelVisible(false);
            iconoCompra.setVisible(false);
        }
    }//GEN-LAST:event_btnCompraMouseExited

    private void btnLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosMouseClicked
        if (!mantenerLibros) {

            mantenerCompra = false;
            selectorCompra.setVisible(false);
            btnCompraDefault();
            iconoCompra.setVisible(false);

            mantenerDetalles = false;
            selectorDetalles.setVisible(false);
            btnDetallesDefatult();
            panelDetalleVisible(false);
            reinicioDetalle();

            mantenerDistribuidor = false;
            selectorDistribuidor.setVisible(false);
            btnDistribuidoresDefault();
            iconoDistribuidor.setVisible(false);

            mantenerFactura = false;
            selectorFactura.setVisible(false);
            btnFacturasDefault();
            iconoFactura.setVisible(false);

            mantenerMetodoPago = false;
            selectorMetodoPago.setVisible(false);
            btnMetodoPagoDefault();
            iconoMetodoPago.setVisible(false);

            mantenerLibros = true;
            selectorLibros.setVisible(true);
            btnLibrosSelected();
            iconoLibro.setVisible(true);
            panelVisible(true);
        } else {
            mantenerLibros = false;
            selectorLibros.setVisible(false);
        }
    }//GEN-LAST:event_btnLibrosMouseClicked

    private void btnDetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetallesMouseClicked
        if (!mantenerDetalles) {

            mantenerCompra = false;
            selectorCompra.setVisible(false);
            btnCompraDefault();
            iconoCompra.setVisible(false);

            mantenerDistribuidor = false;
            selectorDistribuidor.setVisible(false);
            btnDistribuidoresDefault();
            iconoDistribuidor.setVisible(false);

            mantenerFactura = false;
            selectorFactura.setVisible(false);
            btnFacturasDefault();
            iconoFactura.setVisible(false);

            mantenerLibros = false;
            selectorLibros.setVisible(false);
            btnLibrosDefault();
            iconoLibro.setVisible(false);

            mantenerMetodoPago = false;
            selectorMetodoPago.setVisible(false);
            btnMetodoPagoDefault();
            iconoMetodoPago.setVisible(false);

            panelVisible(false);

            mantenerDetalles = true;
            selectorDetalles.setVisible(true);
            btnDetallesSelected();
            panelDetalleVisible(true);
        } else {
            mantenerDetalles = false;
            selectorDetalles.setVisible(false);

        }
    }//GEN-LAST:event_btnDetallesMouseClicked

    private void btnDistribuidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDistribuidoresMouseClicked
        if (!mantenerDistribuidor) {

            mantenerCompra = false;
            selectorCompra.setVisible(false);
            btnCompraDefault();
            iconoCompra.setVisible(false);

            mantenerDetalles = false;
            selectorDetalles.setVisible(false);
            btnDetallesDefatult();
            panelDetalleVisible(false);
            reinicioDetalle();

            mantenerFactura = false;
            selectorFactura.setVisible(false);
            btnFacturasDefault();
            iconoFactura.setVisible(false);

            mantenerLibros = false;
            selectorLibros.setVisible(false);
            btnLibrosDefault();
            iconoLibro.setVisible(false);

            mantenerMetodoPago = false;
            selectorMetodoPago.setVisible(false);
            btnMetodoPagoDefault();
            iconoMetodoPago.setVisible(false);

            mantenerDistribuidor = true;
            selectorDistribuidor.setVisible(true);
            btnDistribuidoresSelected();
            iconoDistribuidor.setVisible(true);
            panelVisible(true);

        } else {
            mantenerDistribuidor = false;
            selectorDistribuidor.setVisible(false);
        }
    }//GEN-LAST:event_btnDistribuidoresMouseClicked

    private void btnFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturasMouseClicked
        if (!mantenerFactura) {

            mantenerCompra = false;
            selectorCompra.setVisible(false);
            btnCompraDefault();
            iconoCompra.setVisible(false);

            mantenerDetalles = false;
            selectorDetalles.setVisible(false);
            btnDetallesDefatult();
            panelDetalleVisible(false);
            reinicioDetalle();

            mantenerDistribuidor = false;
            selectorDistribuidor.setVisible(false);
            btnDistribuidoresDefault();
            iconoDistribuidor.setVisible(false);

            mantenerLibros = false;
            selectorLibros.setVisible(false);
            btnLibrosDefault();
            iconoLibro.setVisible(false);

            mantenerMetodoPago = false;
            selectorMetodoPago.setVisible(false);
            btnMetodoPagoDefault();
            iconoMetodoPago.setVisible(false);

            mantenerFactura = true;
            selectorFactura.setVisible(true);
            btnFacturasSelected();
            iconoFactura.setVisible(true);
            panelVisible(true);
        } else {
            mantenerFactura = false;
            selectorFactura.setVisible(false);
        }
    }//GEN-LAST:event_btnFacturasMouseClicked

    private void btnMetodoPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMetodoPagoMouseClicked
        if (!mantenerMetodoPago) {

            mantenerCompra = false;
            selectorCompra.setVisible(false);
            btnCompraDefault();
            iconoCompra.setVisible(false);

            mantenerDetalles = false;
            selectorDetalles.setVisible(false);
            btnDetallesDefatult();
            panelDetalleVisible(false);
            reinicioDetalle();

            mantenerDistribuidor = false;
            selectorDistribuidor.setVisible(false);
            btnDistribuidoresDefault();
            iconoDistribuidor.setVisible(false);

            mantenerFactura = false;
            selectorFactura.setVisible(false);
            btnFacturasDefault();
            iconoFactura.setVisible(false);

            mantenerLibros = false;
            selectorLibros.setVisible(false);
            btnLibrosDefault();
            iconoLibro.setVisible(false);

            mantenerMetodoPago = true;
            selectorMetodoPago.setVisible(true);
            btnMetodoPagoSelected();
            iconoMetodoPago.setVisible(true);
            panelVisible(true);
        } else {
            mantenerMetodoPago = false;
            selectorMetodoPago.setVisible(false);
        }
    }//GEN-LAST:event_btnMetodoPagoMouseClicked

    private void btnCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseClicked
        if (!mantenerCompra) {

            mantenerDetalles = false;
            selectorDetalles.setVisible(false);
            btnDetallesDefatult();
            panelDetalleVisible(false);
            reinicioDetalle();

            mantenerDistribuidor = false;
            selectorDistribuidor.setVisible(false);
            btnDistribuidoresDefault();
            iconoDistribuidor.setVisible(false);

            mantenerFactura = false;
            selectorFactura.setVisible(false);
            btnFacturasDefault();
            iconoFactura.setVisible(false);

            mantenerLibros = false;
            selectorLibros.setVisible(false);
            btnLibrosDefault();
            iconoLibro.setVisible(false);

            mantenerMetodoPago = false;
            selectorMetodoPago.setVisible(false);
            btnMetodoPagoDefault();
            iconoMetodoPago.setVisible(false);

            mantenerCompra = true;
            selectorCompra.setVisible(true);
            btnCompraSelected();
            iconoCompra.setVisible(true);
            panelVisible(true);
        } else {
            mantenerCompra = false;
            selectorCompra.setVisible(false);
        }
    }//GEN-LAST:event_btnCompraMouseClicked

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        btnRegistrarSelected();
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        btnRegistrarDefault();
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscarSelected();
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscarDefault();
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseEntered
        btnMostrarSelected();
    }//GEN-LAST:event_btnMostrarMouseEntered

    private void btnMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseExited
        btnMostrarDefault();
    }//GEN-LAST:event_btnMostrarMouseExited

    private void btnRegistrarDetalleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarDetalleMouseEntered
        btnRegistrarDetalleSelected();
    }//GEN-LAST:event_btnRegistrarDetalleMouseEntered

    private void btnAutorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutorMouseEntered
        if (!mantenerEditorial & !mantenerCategoria & !mantenerIdioma & !mantenerEstado & !mantenerTitulo) {
            btnAutorSelected();
            panel3Visible(true);
            iconoAutor.setVisible(true);
        }
    }//GEN-LAST:event_btnAutorMouseEntered

    private void btnAutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutorMouseExited
        if (!mantenerAutor & !mantenerCategoria & !mantenerEditorial & !mantenerIdioma & !mantenerEstado & !mantenerTitulo) {
            btnAutorDefault();
            panel3Visible(false);
            iconoAutor.setVisible(false);
        }
    }//GEN-LAST:event_btnAutorMouseExited

    private void btnEditorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorialMouseEntered
        if (!mantenerAutor & !mantenerCategoria & !mantenerIdioma & !mantenerEstado & !mantenerTitulo) {
            btnEditorialSelected();
            panel3Visible(true);
            iconoEditorial.setVisible(true);
        }
    }//GEN-LAST:event_btnEditorialMouseEntered

    private void btnEditorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorialMouseClicked
        if (!mantenerEditorial) {

            mantenerTitulo = false;
            btnTituloDefault();
            iconoTitulo.setVisible(false);
            selectorTitulo.setVisible(false);

            mantenerAutor = false;
            btnAutorDefault();
            iconoAutor.setVisible(false);
            selectorAutor.setVisible(false);

            mantenerCategoria = false;
            btnCategoriaDefault();
            iconoCategoria.setVisible(false);
            selectorCategoria.setVisible(false);

            mantenerIdioma = false;
            btnIdiomaDefault();
            iconoIdioma.setVisible(false);
            selectorIdioma.setVisible(false);

            mantenerEstado = false;
            btnEstadoDefault();
            iconoEstado.setVisible(false);
            selectorEstado.setVisible(false);

            mantenerEditorial = true;
            btnEditorialSelected();
            selectorEditorial.setVisible(true);
            iconoEditorial.setVisible(true);
        } else {
            mantenerEditorial = false;
            selectorEditorial.setVisible(false);
        }
    }//GEN-LAST:event_btnEditorialMouseClicked

    private void btnEditorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditorialMouseExited
        if (!mantenerAutor & !mantenerCategoria & !mantenerEditorial & !mantenerIdioma & !mantenerEstado & !mantenerTitulo) {
            btnEditorialDefault();
            panel3Visible(false);
            iconoEditorial.setVisible(false);
        }
    }//GEN-LAST:event_btnEditorialMouseExited

    private void btnCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriaMouseEntered
        if (!mantenerAutor & !mantenerEditorial & !mantenerIdioma & !mantenerEstado & !mantenerTitulo) {
            btnCategoriaSelected();
            panel3Visible(true);
            iconoCategoria.setVisible(true);
        }
    }//GEN-LAST:event_btnCategoriaMouseEntered

    private void btnCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriaMouseExited
        if (!mantenerAutor & !mantenerCategoria & !mantenerEditorial & !mantenerIdioma & !mantenerEstado & !mantenerTitulo) {
            btnCategoriaDefault();
            panel3Visible(false);
            iconoCategoria.setVisible(false);
        }
    }//GEN-LAST:event_btnCategoriaMouseExited

    private void btnIdiomaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdiomaMouseEntered
        if (!mantenerAutor & !mantenerEditorial & !mantenerCategoria & !mantenerEstado & !mantenerTitulo) {
            btnIdiomaSelected();
            panel3Visible(true);
            iconoIdioma.setVisible(true);
        }
    }//GEN-LAST:event_btnIdiomaMouseEntered

    private void btnIdiomaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdiomaMouseExited
        if (!mantenerAutor & !mantenerCategoria & !mantenerEditorial & !mantenerIdioma & !mantenerEstado & !mantenerTitulo) {
            btnIdiomaDefault();
            panel3Visible(false);
            iconoIdioma.setVisible(false);
        }
    }//GEN-LAST:event_btnIdiomaMouseExited

    private void btnEstadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoMouseEntered
        if (!mantenerAutor & !mantenerEditorial & !mantenerCategoria & !mantenerIdioma & !mantenerTitulo) {
            btnEstadoSelected();
            panel3Visible(true);
            iconoEstado.setVisible(true);
        }
    }//GEN-LAST:event_btnEstadoMouseEntered

    private void btnEstadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoMouseExited
        if (!mantenerAutor & !mantenerCategoria & !mantenerEditorial & !mantenerIdioma & !mantenerEstado & !mantenerTitulo) {
            btnEstadoDefault();
            panel3Visible(false);
            iconoEstado.setVisible(false);
        }
    }//GEN-LAST:event_btnEstadoMouseExited

    private void btnAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutorMouseClicked
        if (!mantenerAutor) {

            mantenerTitulo = false;
            btnTituloDefault();
            iconoTitulo.setVisible(false);
            selectorTitulo.setVisible(false);

            mantenerEditorial = false;
            btnEditorialDefault();
            iconoEditorial.setVisible(false);
            selectorEditorial.setVisible(false);

            mantenerCategoria = false;
            btnCategoriaDefault();
            iconoCategoria.setVisible(false);
            selectorCategoria.setVisible(false);

            mantenerIdioma = false;
            btnIdiomaDefault();
            iconoIdioma.setVisible(false);
            selectorIdioma.setVisible(false);

            mantenerEstado = false;
            btnEstadoDefault();
            iconoEstado.setVisible(false);
            selectorEstado.setVisible(false);

            mantenerAutor = true;
            btnAutorSelected();
            selectorAutor.setVisible(true);
            iconoAutor.setVisible(true);
        } else {
            mantenerAutor = false;
            selectorAutor.setVisible(false);
        }
    }//GEN-LAST:event_btnAutorMouseClicked

    private void btnCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriaMouseClicked
        if (!mantenerCategoria) {

            mantenerTitulo = false;
            btnTituloDefault();
            iconoTitulo.setVisible(false);
            selectorTitulo.setVisible(false);

            mantenerAutor = false;
            btnAutorDefault();
            iconoAutor.setVisible(false);
            selectorAutor.setVisible(false);

            mantenerEditorial = false;
            btnEditorialDefault();
            iconoEditorial.setVisible(false);
            selectorEditorial.setVisible(false);

            mantenerIdioma = false;
            btnIdiomaDefault();
            iconoIdioma.setVisible(false);
            selectorIdioma.setVisible(false);

            mantenerEstado = false;
            btnEstadoDefault();
            iconoEstado.setVisible(false);
            selectorEstado.setVisible(false);

            mantenerCategoria = true;
            btnCategoriaSelected();
            selectorCategoria.setVisible(true);
            iconoCategoria.setVisible(true);
        } else {
            mantenerCategoria = false;
            selectorCategoria.setVisible(false);
        }
    }//GEN-LAST:event_btnCategoriaMouseClicked

    private void btnIdiomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdiomaMouseClicked
        if (!mantenerIdioma) {

            mantenerTitulo = false;
            btnTituloDefault();
            iconoTitulo.setVisible(false);
            selectorTitulo.setVisible(false);

            mantenerAutor = false;
            btnAutorDefault();
            iconoAutor.setVisible(false);
            selectorAutor.setVisible(false);

            mantenerEditorial = false;
            btnEditorialDefault();
            iconoEditorial.setVisible(false);
            selectorEditorial.setVisible(false);

            mantenerCategoria = false;
            btnCategoriaDefault();
            iconoCategoria.setVisible(false);
            selectorCategoria.setVisible(false);

            mantenerEstado = false;
            btnEstadoDefault();
            iconoEstado.setVisible(false);
            selectorEstado.setVisible(false);

            mantenerIdioma = true;
            btnIdiomaSelected();
            selectorIdioma.setVisible(true);
            iconoIdioma.setVisible(true);
        } else {
            mantenerIdioma = false;
            selectorIdioma.setVisible(false);
        }
    }//GEN-LAST:event_btnIdiomaMouseClicked

    private void btnEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoMouseClicked
        if (!mantenerEstado) {

            mantenerTitulo = false;
            btnTituloDefault();
            iconoTitulo.setVisible(false);
            selectorTitulo.setVisible(false);

            mantenerAutor = false;
            btnAutorDefault();
            iconoAutor.setVisible(false);
            selectorAutor.setVisible(false);

            mantenerEditorial = false;
            btnEditorialDefault();
            iconoEditorial.setVisible(false);
            selectorEditorial.setVisible(false);

            mantenerCategoria = false;
            btnCategoriaDefault();
            iconoCategoria.setVisible(false);
            selectorCategoria.setVisible(false);

            mantenerIdioma = false;
            btnIdiomaDefault();
            iconoIdioma.setVisible(false);
            selectorIdioma.setVisible(false);

            mantenerEstado = true;
            btnEstadoSelected();
            selectorEstado.setVisible(true);
            iconoEstado.setVisible(true);
        } else {
            mantenerEstado = false;
            selectorEstado.setVisible(false);
        }
    }//GEN-LAST:event_btnEstadoMouseClicked

    private void btnRegistrarDetalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarDetalleMouseExited
        btnRegistrarDetalleDefault();
    }//GEN-LAST:event_btnRegistrarDetalleMouseExited

    private void btnBuscarDetalleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDetalleMouseEntered
        btnBuscarDetalleSelected();
    }//GEN-LAST:event_btnBuscarDetalleMouseEntered

    private void btnBuscarDetalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDetalleMouseExited
        btnBuscarDetalleDefault();
    }//GEN-LAST:event_btnBuscarDetalleMouseExited

    private void btnMostrarDetalleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarDetalleMouseEntered
        btnMostrarDetalleSelected();
    }//GEN-LAST:event_btnMostrarDetalleMouseEntered

    private void btnMostrarDetalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarDetalleMouseExited
        btnMostrarDetalleDefault();
    }//GEN-LAST:event_btnMostrarDetalleMouseExited

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        if (mantenerLibros) {
            btnBuscarDefault();
            Principal.principal.BuscarLibro();
        }
        if(mantenerDistribuidor){
            btnBuscarDefault();
            Principal.principal.buscarDistribuidor();
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnRegistrarDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarDetalleMouseClicked
        if (mantenerAutor) {
            btnRegistrarDetalleDefault();
            Principal.principal.registrarAutor();
        }
        if (mantenerEditorial) {
            btnRegistrarDetalleDefault();
            Principal.principal.registrarEditorial();
        }
        if (mantenerCategoria) {
            btnRegistrarDetalleDefault();
            Principal.principal.registrarCategoria();
        }
        if (mantenerIdioma) {
            btnRegistrarDetalleDefault();
            Principal.principal.registrarIdioma();
        }
        if (mantenerEstado) {
            btnRegistrarDetalleDefault();
            Principal.principal.registrarEstado();
        }
        if (mantenerTitulo) {
            btnRegistrarDetalleDefault();
            Principal.principal.registrarTitulo();
        }
    }//GEN-LAST:event_btnRegistrarDetalleMouseClicked

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        if (mantenerLibros) {
            btnRegistrarDefault();
            Principal.principal.registrarLibro();
        }
        if (mantenerDistribuidor) {
            btnRegistrarDefault();
            Principal.principal.registrarDistribuidor();
        }
        if (mantenerFactura) {
            btnRegistrarDefault();
            Principal.principal.registrarFactura();
        }
        if (mantenerMetodoPago) {
            btnRegistrarDefault();
            Principal.principal.registrarMetodoPago();
        }
        if (mantenerCompra) {
            btnRegistrarDefault();
            Principal.principal.TipoTransaccion();
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void wallpaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallpaperMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_wallpaperMouseClicked

    private void btnMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseClicked
        if (mantenerLibros) {
            btnMostrarDefault();
            Principal.principal.MostratTodoLibros();
        }
        if(mantenerDistribuidor){
            btnMostrarDefault();
            Principal.principal.MostrarTodosDistribuidor();
        }
    }//GEN-LAST:event_btnMostrarMouseClicked

    private void btnTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTituloMouseClicked

        if (!mantenerTitulo) {

            mantenerEstado = false;
            btnEstadoDefault();
            selectorEstado.setVisible(false);
            iconoEstado.setVisible(false);

            mantenerAutor = false;
            btnAutorDefault();
            iconoAutor.setVisible(false);
            selectorAutor.setVisible(false);

            mantenerEditorial = false;
            btnEditorialDefault();
            iconoEditorial.setVisible(false);
            selectorEditorial.setVisible(false);

            mantenerCategoria = false;
            btnCategoriaDefault();
            iconoCategoria.setVisible(false);
            selectorCategoria.setVisible(false);

            mantenerIdioma = false;
            btnIdiomaDefault();
            iconoIdioma.setVisible(false);
            selectorIdioma.setVisible(false);
            
            mantenerTitulo = true;
            btnTituloSelected();
            iconoTitulo.setVisible(true);
            selectorTitulo.setVisible(true);

        } else {
            mantenerTitulo = false;
            selectorTitulo.setVisible(false);
        }

    }//GEN-LAST:event_btnTituloMouseClicked

    private void btnTituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTituloMouseEntered

        if (!mantenerAutor & !mantenerEditorial & !mantenerCategoria & !mantenerIdioma & !mantenerEstado) {
            btnTituloSelected();
            panel3Visible(true);
            iconoTitulo.setVisible(true);
        }
    }//GEN-LAST:event_btnTituloMouseEntered

    private void btnTituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTituloMouseExited

        if (!mantenerAutor & !mantenerCategoria & !mantenerEditorial & !mantenerIdioma & !mantenerEstado & !mantenerTitulo) {
            btnTituloDefault();
            panel3Visible(false);
            iconoTitulo.setVisible(false);
        }
    }//GEN-LAST:event_btnTituloMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAutor;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnBuscarDetalle;
    private javax.swing.JLabel btnCategoria;
    private javax.swing.JLabel btnCompra;
    private javax.swing.JLabel btnDetalles;
    private javax.swing.JLabel btnDistribuidores;
    private javax.swing.JLabel btnEditorial;
    private javax.swing.JLabel btnEstado;
    private javax.swing.JLabel btnFacturas;
    private javax.swing.JLabel btnIdioma;
    private javax.swing.JLabel btnLibros;
    private javax.swing.JLabel btnMetodoPago;
    private javax.swing.JLabel btnMostrar;
    private javax.swing.JLabel btnMostrarDetalle;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JLabel btnRegistrarDetalle;
    private javax.swing.JLabel btnTitulo;
    private javax.swing.JLabel contenedor3;
    private javax.swing.JLabel contenedorPrincipal;
    private javax.swing.JLabel contenedorSecundario;
    private javax.swing.JLabel contenedorSecundarioDetalle;
    private javax.swing.JLabel iconoAutor;
    private javax.swing.JLabel iconoCategoria;
    private javax.swing.JLabel iconoCompra;
    private javax.swing.JLabel iconoDistribuidor;
    private javax.swing.JLabel iconoEditorial;
    private javax.swing.JLabel iconoEstado;
    private javax.swing.JLabel iconoFactura;
    private javax.swing.JLabel iconoIdioma;
    private javax.swing.JLabel iconoLibro;
    private javax.swing.JLabel iconoMetodoPago;
    private javax.swing.JLabel iconoTitulo;
    private javax.swing.JLabel selectorAutor;
    private javax.swing.JLabel selectorCategoria;
    private javax.swing.JLabel selectorCompra;
    private javax.swing.JLabel selectorDetalles;
    private javax.swing.JLabel selectorDistribuidor;
    private javax.swing.JLabel selectorEditorial;
    private javax.swing.JLabel selectorEstado;
    private javax.swing.JLabel selectorFactura;
    private javax.swing.JLabel selectorIdioma;
    private javax.swing.JLabel selectorLibros;
    private javax.swing.JLabel selectorMetodoPago;
    private javax.swing.JLabel selectorTitulo;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
