/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorDistribuidor;
import Modelo.Distribuidor;
import java.awt.Color;
import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParsePosition;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class RegistrarDistribuidor extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    public RegistrarDistribuidor() {

        initComponents();
        this.setPreferredSize(Principal.dimension);
        this.setMinimumSize(Principal.dimension);
        this.setMaximumSize(Principal.dimension);
        errorRut.setVisible(false);

    }

    private void configurarCalendario() {

    }
    
    private void limpiar(){
        txtDireccion.setText("");
        txtNombreEmpresa.setText("");
        txtRut.setText("");
        txtTelefono.setText("");
        
    }
    private void buscaExistencia(){
        
        
        if(new ControladorDistribuidor().existe(txtRut.getText())){
            errorRut.setVisible(true);
        }
        else{
            errorRut.setVisible(false);
            System.out.println("Apretaste algo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombreEmpresa = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        calendario = new com.toedter.calendar.JDateChooser();
        errorRut = new javax.swing.JLabel();
        contenedorSecundario = new javax.swing.JLabel();
        contenedorPrincipal = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1382, 744));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(66, 66, 66));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Distribuidor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Felix Titling", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rut:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 60, 30, 15);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Empresa:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 100, 130, 15);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dirección:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 130, 70, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 180, 67, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de Asociación:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 220, 150, 30);

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutKeyReleased(evt);
            }
        });
        jPanel1.add(txtRut);
        txtRut.setBounds(200, 60, 170, 23);
        jPanel1.add(txtNombreEmpresa);
        txtNombreEmpresa.setBounds(200, 100, 180, 23);
        jPanel1.add(txtDireccion);
        txtDireccion.setBounds(200, 140, 180, 23);
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(200, 180, 190, 23);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar);
        btnRegistrar.setBounds(250, 380, 150, 31);
        jPanel1.add(calendario);
        calendario.setBounds(200, 220, 190, 29);

        errorRut.setForeground(new java.awt.Color(255, 0, 0));
        errorRut.setText("ya se encuentra registrado!");
        jPanel1.add(errorRut);
        errorRut.setBounds(390, 60, 200, 20);

        add(jPanel1);
        jPanel1.setBounds(540, 110, 660, 490);

        contenedorSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/contenedor-secundario.png"))); // NOI18N
        add(contenedorSecundario);
        contenedorSecundario.setBounds(480, 60, 770, 590);

        contenedorPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/contenedor-main.png"))); // NOI18N
        add(contenedorPrincipal);
        contenedorPrincipal.setBounds(40, 70, 300, 580);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/wallpapers/wallpaper.jpg"))); // NOI18N
        wallpaper.setPreferredSize(Principal.dimension);
        add(wallpaper);
        wallpaper.setBounds(0, 0, 2558, 1562);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Distribuidor d = new Distribuidor(txtRut.getText(), txtNombreEmpresa.getText(), txtDireccion.getText(), txtTelefono.getText(), new java.sql.Date(calendario.getDate().getYear(), calendario.getDate().getMonth(), calendario.getDate().getDay()));
        if (new ControladorDistribuidor().registrar(d)) {
            JOptionPane.showMessageDialog(null, "Se ha registrado correctamente");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "algo salio mal");
        }
        

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed

    }//GEN-LAST:event_txtRutActionPerformed

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
      //  buscaExistencia();
        
    }//GEN-LAST:event_txtRutKeyTyped

    private void txtRutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyReleased
        buscaExistencia();
    }//GEN-LAST:event_txtRutKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JLabel contenedorPrincipal;
    private javax.swing.JLabel contenedorSecundario;
    private javax.swing.JLabel errorRut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
