/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorArriendo;
import Controlador.ControladorCliente;
import Controlador.ControladorLibro;
import Controlador.ControladorTitulo;
import Modelo.Arriendo;
import Modelo.Cliente;
import Modelo.Libro;
import Modelo.TituloLibro;
import java.util.Date;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class RegistrarArriendo extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    private ArrayList<Libro> listaArrendar = new ControladorLibro().LibrosArriendo();
    private ArrayList<Libro> disponible = new ArrayList<>();
    private ArrayList<String> listaSeries = new ArrayList<>();
    private ArrayList<Cliente> listaClientes = new ControladorCliente().listado();
    private int id = new ControladorArriendo().asignarId();
    private DefaultTableModel modeloTabla = new DefaultTableModel(null, new String[]{"Libros"});

    public RegistrarArriendo() {
        initComponents();
        this.setPreferredSize(Principal.dimension);
        this.setMinimumSize(Principal.dimension);
        this.setMaximumSize(Principal.dimension);
        boxTitulos();
        cargarBoxCliente();
        labelIdArriendo.setText(String.valueOf(id));

    }

    private void limpiarTexto() {
        txtCostoArriendo.setText("");

    }

    private void cargarBoxCliente() {

        for (int i = 0; i < listaClientes.size(); i++) {
            boxCliente.addItem(listaClientes.get(i).getRut());
        }
    }

    private boolean comprobar() {
        boolean existe = false;

        /* for (int i = 0; i < listaSeries.size(); i++) {
            if (listaSeries.get(i).equals((String) boxNroSerie.getSelectedItem())) {
                existe = true;
            }
        }*/
        int totalRows = lista.getRowCount();
        for (int i = 0; i < totalRows; i++) {
            if (boxNroSerie.getSelectedItem().equals(lista.getValueAt(i, 0))) {
                existe = true;
            }
        }

        return existe;
    }

    private void eliminar(int index) {
        ArrayList<String> aux = new ArrayList<>();
        for (int i = 0; i < listaSeries.size(); i++) {
            if (i != index) {
                aux.add(listaSeries.get(i));
            }
        }
        listaSeries = aux;
    }

    private void btnVolverDefault() {
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/volver-default.png")));
    }

    private void btnVolverSelected() {
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/volver-selected.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void boxTitulos() {
        ArrayList<TituloLibro> listaTituloDisponible = new ArrayList<>();
        ArrayList<TituloLibro> listaTitulo = new ControladorTitulo().listado();
        for (int i = 0; i < listaTitulo.size(); i++) {
            String titulo = listaTitulo.get(i).getTitulo();
            for (int j = 0; j < listaArrendar.size(); j++) {
                if (titulo.equals(listaArrendar.get(j).getTitulo())) {
                    boolean existe = false;
                    for (int x = 0; x < listaTituloDisponible.size(); x++) {
                        if (titulo.equals(listaTituloDisponible.get(x).getTitulo())) {
                            existe = true;
                        }
                    }
                    if (!existe) {
                        listaTituloDisponible.add(listaTitulo.get(i));
                    }
                }
            }
        }
        for (int i = 0; i < listaTituloDisponible.size(); i++) {
            boxTitulo.addItem(listaTituloDisponible.get(i).getTitulo());
        }
    }

    private void btnConfirmarDefault() {
        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/confirmar-default.png")));
    }

    private void btnConfirmarSelected() {
        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/confirmar-selected.png")));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        boxTitulo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        boxNroSerie = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnVaciar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fechaDevolucion = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtCostoArriendo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        boxCliente = new javax.swing.JComboBox<>();
        btnConfirmar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelIdArriendo = new javax.swing.JLabel();
        contenedorSecundario = new javax.swing.JLabel();
        btnVolver = new javax.swing.JLabel();
        contenedorPrincipal = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1382, 744));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(66, 66, 66));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Arriendo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Felix Titling", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione Título:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 60, 100, 20);

        boxTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTituloActionPerformed(evt);
            }
        });
        jPanel1.add(boxTitulo);
        boxTitulo.setBounds(160, 60, 230, 26);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nro. Serie:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(91, 100, 60, 20);

        jPanel1.add(boxNroSerie);
        boxNroSerie.setBounds(160, 100, 230, 26);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(220, 140, 76, 32);

        lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Libro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(lista);
        if (lista.getColumnModel().getColumnCount() > 0) {
            lista.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(423, 60, 220, 140);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(420, 210, 76, 32);

        btnVaciar.setText("Vaciar");
        jPanel1.add(btnVaciar);
        btnVaciar.setBounds(560, 210, 67, 32);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha Devolucion:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 220, 110, 30);
        jPanel1.add(fechaDevolucion);
        fechaDevolucion.setBounds(160, 220, 190, 29);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Costo Arriendo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 270, 100, 20);
        jPanel1.add(txtCostoArriendo);
        txtCostoArriendo.setBounds(160, 270, 140, 24);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cliente:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 320, 50, 20);

        jPanel1.add(boxCliente);
        boxCliente.setBounds(160, 320, 140, 26);

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/confirmar-default.png"))); // NOI18N
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseExited(evt);
            }
        });
        jPanel1.add(btnConfirmar);
        btnConfirmar.setBounds(450, 390, 170, 50);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id Arriendo:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(500, 20, 70, 16);

        labelIdArriendo.setForeground(new java.awt.Color(255, 255, 255));
        labelIdArriendo.setText("jLabel7");
        jPanel1.add(labelIdArriendo);
        labelIdArriendo.setBounds(580, 20, 41, 16);

        add(jPanel1);
        jPanel1.setBounds(540, 110, 660, 490);

        contenedorSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/contenedor-secundario.png"))); // NOI18N
        add(contenedorSecundario);
        contenedorSecundario.setBounds(480, 60, 770, 590);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/botones/volver-default.png"))); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        add(btnVolver);
        btnVolver.setBounds(110, 570, 170, 50);

        contenedorPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/contenedores/contenedor-main.png"))); // NOI18N
        add(contenedorPrincipal);
        contenedorPrincipal.setBounds(40, 70, 300, 580);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/wallpapers/wallpaper.jpg"))); // NOI18N
        wallpaper.setPreferredSize(Principal.dimension);
        add(wallpaper);
        wallpaper.setBounds(0, 0, 2558, 1562);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        limpiarTexto();
        btnVolverDefault();
        Principal.principal.TipoTransaccion();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolverSelected();
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolverDefault();
    }//GEN-LAST:event_btnVolverMouseExited

    private void boxTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTituloActionPerformed
        int itemCount = boxNroSerie.getItemCount();

        for (int i = 0; i < itemCount; i++) {
            boxNroSerie.removeItemAt(0);
        }

        disponible = new ArrayList<>();
        String titulo = (String) boxTitulo.getSelectedItem();
        System.out.println("titulo seleccionado: " + titulo);
        for (int i = 0; i < listaArrendar.size(); i++) {
            if (titulo.equals(listaArrendar.get(i).getTitulo())) {
                disponible.add(listaArrendar.get(i));
            }

        }
        for (int i = 0; i < disponible.size(); i++) {
            boxNroSerie.addItem(disponible.get(i).getNro_serie());
        }
    }//GEN-LAST:event_boxTituloActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (comprobar()) {
            JOptionPane.showMessageDialog(null, "Ya existe este libro en la lista");

        } else {
            //listaSeries.add((String) boxNroSerie.getSelectedItem());
            modeloTabla.addRow(new Object[]{boxNroSerie.getSelectedItem()});
            System.out.println("tamaño de la lista: " + listaSeries.size());
            //Object[][] model = new Object[1][listaSeries.size()];
            /* for (int i = 0; i < listaSeries.size(); i++) {
                System.out.println("Agregarndo a la matriz model[0][" + i + "] el valor: " + listaSeries.get(i));
                //model[0][i] = ;
                
            }*/

            //modeloTabla.setDataVector(model, new String []{"Libro"});
            lista.setModel(modeloTabla);
            //tablaPrueba.setModel(modeloTabla);
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private String getFechaHoy() {
        String fecha;      
        Date hoy = new Date();
        String dia = String.valueOf(hoy.getDate());
        String mes = String.valueOf(hoy.getMonth()+1);
        String ano = String.valueOf(hoy.getYear()+1900);

        fecha = ano + "-" + mes + "-" + dia;

        return fecha;
    }

    private String getFechaDevolucion() {
        String fecha;
        String dia = String.valueOf(fechaDevolucion.getDate().getDate());
        String mes = String.valueOf(fechaDevolucion.getDate().getMonth()+1);
        String ano = String.valueOf(fechaDevolucion.getDate().getYear()+1900);

        fecha = ano + "-" + mes + "-" + dia;

        return fecha;
    }

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int row = -1;
        row = lista.getSelectedRow();
        if (row != -1) {
            lista.removeRowSelectionInterval(row, row);
            /* lista.get
            eliminar(row);
            Object[][] model = new Object[1][listaSeries.size()];
            for (int i = 0; i < listaSeries.size(); i++) {
                model[0][i] = listaSeries.get(i);
            }

            lista.setModel(new DefaultTableModel(model, new String[]{"Libro"}));
             */
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un item de la lista");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseEntered
        btnConfirmarSelected();
    }//GEN-LAST:event_btnConfirmarMouseEntered

    private void btnConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseExited
        btnConfirmarDefault();
    }//GEN-LAST:event_btnConfirmarMouseExited

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        int idCliente = 0;
        for (int i = 0; i < listaClientes.size(); i++) {
            if (listaClientes.get(i).getRut().equals((String) boxCliente.getSelectedItem())) {
                idCliente = listaClientes.get(i).getId();

                if (new ControladorArriendo().crear(new Arriendo(id, getFechaHoy() ,getFechaDevolucion(), Integer.parseInt(txtCostoArriendo.getText()), idCliente, 1))) {
                    int size = lista.getRowCount();
                    for (int j = 0; j < size; j++) {
                        if (new ControladorLibro().agregarIdArriendo((String) lista.getModel().getValueAt(j, 0), id)) {
                            JOptionPane.showMessageDialog(null, "Se ha guardado exitosamente");
                        } else {
                            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al hacer cambio de idarriendo en el libro");
                        }

                    }
                    Principal.principal.Arriendo();
                } else {
                    JOptionPane.showMessageDialog(null, "error al registrar el arriendo");
                }
            }

        }

        
    }//GEN-LAST:event_btnConfirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCliente;
    private javax.swing.JComboBox<String> boxNroSerie;
    private javax.swing.JComboBox<String> boxTitulo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel btnConfirmar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JLabel contenedorPrincipal;
    private javax.swing.JLabel contenedorSecundario;
    private com.toedter.calendar.JDateChooser fechaDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelIdArriendo;
    private javax.swing.JTable lista;
    private javax.swing.JTextField txtCostoArriendo;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
